name: Build And Deploy
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: /home/runner/work
        steps:
						- ok:
							run: ls
            - name: Build site
              run: npm run build

    deploy:
        if: github.ref == 'refs/heads/main'
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v2
              with:
                  name: build
                  path: build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: gh-pages
                  publish_dir: ./build
